use std::convert::Infallible;

use axum::{
    extract::{Path, Query, State},
    http::{header, HeaderMap, HeaderValue, StatusCode},
    response::{
        sse::{Event, KeepAlive, Sse},
        IntoResponse, Response,
    },
    Json,
};
use futures::Stream;
use serde::Deserialize;
use tokio_stream::{wrappers::BroadcastStream, StreamExt as _};

use crate::auth::service as auth_service;
use crate::common::PaginatedResponse;
use crate::errors::AppError;
use crate::state::AppState;

use super::models::{AttendanceEventResponse, EventListQuery};
use super::service;

/// GET /api/v1/events/stream — Server-Sent Events feed of attendance events.
///
/// EventSource (browser API) cannot send custom headers, so JWT is passed as
/// `?token=<access_jwt>` query param (T-4-02 — accepted risk on-premise).
/// The handler validates the JWT itself instead of relying on require_auth
/// middleware; this route is therefore registered in public_routes in main.rs.
#[derive(Deserialize)]
pub struct StreamQuery {
    pub token: String,
}

pub async fn events_stream(
    State(state): State<AppState>,
    Query(q): Query<StreamQuery>,
) -> Result<Sse<impl Stream<Item = Result<Event, Infallible>>>, AppError> {
    // Validate access JWT from query param
    auth_service::verify_access_token(&q.token, state.config.jwt_secret.as_bytes())
        .map_err(|_| AppError::Unauthorized)?;

    let rx = state
        .event_broadcast
        .as_ref()
        .ok_or_else(|| AppError::Internal(anyhow::anyhow!("event_broadcast not initialised")))?
        .subscribe();

    let stream = BroadcastStream::new(rx).filter_map(|res| match res {
        Ok(payload) => Event::default().json_data(payload).ok().map(Ok),
        Err(_) => None, // Lagged or closed — skip
    });

    Ok(Sse::new(stream).keep_alive(KeepAlive::default()))
}

/// GET /api/v1/events — paginated list of attendance events with filters
/// (employee_id, device_id, from, to, include_unknown). Viewer and above per D-15.
pub async fn list_events(
    State(state): State<AppState>,
    Query(q): Query<EventListQuery>,
) -> Result<Json<PaginatedResponse<AttendanceEventResponse>>, AppError> {
    let conn = state.db.connect().map_err(|e| AppError::Internal(e.into()))?;
    let result = service::list(&conn, q).await?;
    Ok(Json(result))
}

/// GET /api/v1/events/:id — single event by id. Viewer and above per D-15.
pub async fn get_event(
    State(state): State<AppState>,
    Path(id): Path<String>,
) -> Result<Json<AttendanceEventResponse>, AppError> {
    let conn = state.db.connect().map_err(|e| AppError::Internal(e.into()))?;
    Ok(Json(service::get_by_id(&conn, &id).await?))
}

/// GET /api/v1/events/:id/photo — stream the event JPEG.
///
/// Defence in depth (T-2-06): `photo_path` is server-generated by the persist
/// helper from a UUID + ISO date, so untrusted clients never control it. Still,
/// we reject any stored value containing `..` or starting with `/`, then
/// canonicalize the resolved absolute path and verify it stays under
/// `state.paths.events_root` before reading bytes. If canonicalize/read fails,
/// we return 404 with `EVENT_PHOTO_NOT_FOUND` (never 500) so a missing/tampered
/// file never leaks as an internal error.
pub async fn get_event_photo(
    State(state): State<AppState>,
    Path(id): Path<String>,
) -> Result<Response, AppError> {
    let conn = state.db.connect().map_err(|e| AppError::Internal(e.into()))?;
    let relpath = service::get_photo_path(&conn, &id).await?;

    if relpath.contains("..") || relpath.starts_with('/') {
        tracing::warn!(
            event_id = %id,
            relpath = %relpath,
            "rejecting photo path with traversal or absolute path marker"
        );
        return Err(AppError::NotFound {
            code: "EVENT_PHOTO_NOT_FOUND",
            message: "Photo not available".to_string(),
        });
    }

    let root = state.paths.events_root.clone();
    let root_canonical = root.canonicalize().map_err(|e| {
        tracing::error!(events_root = ?root, error = %e, "events_root canonicalize failed");
        AppError::NotFound {
            code: "EVENT_PHOTO_NOT_FOUND",
            message: "Photo not available".to_string(),
        }
    })?;

    let full = root_canonical.join(&relpath);
    let canonical = match full.canonicalize() {
        Ok(p) => p,
        Err(_) => {
            return Err(AppError::NotFound {
                code: "EVENT_PHOTO_NOT_FOUND",
                message: "Photo not found on disk".to_string(),
            });
        }
    };

    if !canonical.starts_with(&root_canonical) {
        tracing::error!(event_id = %id, ?canonical, ?root_canonical,
            "canonicalized photo path escapes events_root — rejecting");
        return Err(AppError::NotFound {
            code: "EVENT_PHOTO_NOT_FOUND",
            message: "Photo not available".to_string(),
        });
    }

    let bytes = tokio::fs::read(&canonical).await.map_err(|_| AppError::NotFound {
        code: "EVENT_PHOTO_NOT_FOUND",
        message: "Photo not found on disk".to_string(),
    })?;

    let mut headers = HeaderMap::new();
    headers.insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("image/jpeg"),
    );
    Ok((StatusCode::OK, headers, bytes).into_response())
}
